### ISSUE TITLE
Crossbow texture not working when it's loaded [has a projectile].

### ISSUE THREAD

**Issue by Kal-xyz** [VixelCreates/VanillaEvolved#1]
https://github.com/VixelCreates/VanillaEvolved/assets/44576050/73ee7b98-c0a9-48f6-870c-cedc06d57a2f

**Comment by VixelCreates** [comment]
Hi there.
Sorry for the late reply and thanks for the report.
There doesn't seem to be any problems as far as I can tell.
Probably some kind of interference with another mod/resource pack.

**Comment by Kal-xyz** [comment]
Oh alright, my bad then.
