### ISSUE TITLE
Missing north/south faces for block model rail_curved

### ISSUE THREAD

**Issue by hexakon** [VixelCreates/VanillaEvolved#10]
![image](https://github.com/user-attachments/assets/f91183eb-23e5-41d3-a0c7-a4b9cfca941e)

Issue is present in 1.13.0 release.

In case it helps, I managed to fix it manually by going into `assets/minecraft/models/block/rail_curved.json` and:

- changed line 65 to `"north": {"uv": [5, 10, 6, 8], "rotation": 270, "texture": "#0"},`
- changed line 67 to `"south": {"uv": [6, 10, 7, 8], "rotation": 90, "texture": "#0"},`

**Comment by VixelCreates** [comment]
Hi! Thanks for reporting this issue
i'll add a fix for the next update

**Comment by hexakon** [comment]
Thanks! Incredibly lovely resource pack overall, this is just a nitpick :)
