### ISSUE TITLE
Brown Candle texture messed up.

### ISSUE THREAD

**Issue by TryeTaken** [VixelCreates/VanillaEvolved#12]
Hey, idk if its a me issue, but the brown candle texture is messed up. It had no shading at all and when i turn on my shaders (Complimentary Shaders Reimagined, but i have used other shaders and same issue) The texture completely disappears.
I have tried turning the shaders and texture pack on and off, I have tried leaving the game and coming back, i have also tried taking it out of my modpack and re-downloading, and repairing my modpack (I use modrinth) and none of this has worked. I cant update the modpack anymore, I am on minecraft version 1.20.1 with Forge as my modloader and Vanilla Evolved 1.9.0. 

![image](https://github.com/user-attachments/assets/edcd4db0-d653-4049-bfe5-032db17996c1)

![image](https://github.com/user-attachments/assets/7defddea-ebe7-402f-9daf-e0bf0f1c8e0b)

I hope you can help :)

**Comment by TryeTaken** [comment]
Oh! i forgot to add, all the other candles work!

**Comment by VixelCreates** [comment]
Hi!
Thanks for reporting the issue
i'll add the fix for the next update
here is the file if you need:
[VanillaEvolved.zip](https://github.com/user-attachments/files/17284886/VanillaEvolved.zip)

**Comment by TryeTaken** [comment]
> Hi! Thanks for reporting the issue i'll add the fix for the next update here is the file if you need: [VanillaEvolved.zip](https://github.com/user-attachments/files/17284886/VanillaEvolved.zip)

Hey! Thank you so much!! You got to me so quick, I appriciate it! I can now enjoy my little candles!!

**Comment by VixelCreates** [comment]
You're Welcome! ❤️
