### ISSUE TITLE
[Bug] Baked potato textures can be easily confused with raw potatoes

### ISSUE THREAD

**Issue by chemlzh** [VixelCreates/VanillaEvolved#13]
At version ≤1.16.0, the only difference between baked and raw potatoes is that baked version is brighter and a little larger. This might cause confusion, especially when raw potatoes are used to trade with peasant villagers. Can you modify baked potato textures to make them more distinguishable? I'll very appreciate it!

![(J7X7D3ZVW7E{MK6KVFL87B](https://github.com/user-attachments/assets/3912de3b-2627-4b08-96e2-cf0c7d090309)

**Comment by VixelCreates** [comment]
Hi! Thanks for the feedback
i'll change this for the next update
