### ISSUE TITLE
[Request] Allow glow berry vines to be more see through

### ISSUE THREAD

**Issue by OS-Void** [VixelCreates/VanillaEvolved#2]
Hello, I recently wanted to start using a resourcepack and came across this one, I'm loving it, but if the only thing I could request to change a little would be the Glow berries growing from the ceiling, their vines/greenery could be more see through.

This is a combination of glow berries and regular vines:

![2024-01-15_18 08 31](https://github.com/VixelCreates/VanillaEvolved/assets/5094754/b0a6b4f1-99c9-4108-93ad-890ec71d74c9)

**Comment by VixelCreates** [comment]
Hi!
Thank you for your feedback
There will be some improvements to glowberry vines in the next update.
