### ISSUE TITLE
VanillaEvolved_1.10.0 Failed to load or just stuck on loading screen minecraft Fabric 1.21.

### ISSUE THREAD

**Issue by RoyVDBerg** [VixelCreates/VanillaEvolved#6]
When i launch minecraft Fabric 1.21 with a few mods most recourse packs work but when i add "VanillaEvolved_1.10.0" it Fails to load.
When i as you see in screenshot load it alone it's stuck on the last bit it has to load has been 15~min. 
![image](https://github.com/VixelCreates/VanillaEvolved/assets/35835518/73f8c04a-866c-4b16-ae21-028ba43fa9be)
Here are the mods i have installed all or most of them are client side.
![image](https://github.com/VixelCreates/VanillaEvolved/assets/35835518/c8b7ba62-2765-4e78-8720-04dcfa2ccf50)
All mods should be latest version and work with different Recourse pack just can't figure out why not with VanillaEvolved.

**Comment by RoyVDBerg** [comment]
I found something out in my Fabric 1.21 that any other recourse pack that's not compatible at all will either just say load failure or also get stuck on loading screen.

**Comment by VixelCreates** [comment]
Hi, thanks for reporting this.
Based on a recent report, it is possible that the continuity mod is causing this problem.
I personally haven't had any issues with this mod during testing.
You could check the log files for the minercaft instance you are having problems with and look for any incompatibilities and then report back.
You can also send me your log file, but log files may contain sensitive information, so I encourage you to check this yourself if you can.

**Comment by RoyVDBerg** [comment]
Will take a look.

**Comment by RoyVDBerg** [comment]
I found a solution but now i got another problem. I first loaded the Resource pack without the Continuity packs and it loaded, then i added the Continuity packs and it works, but when i open my inventory in game i get a crash that says "The game crashed whilst rendering entity in world
Error: java.lang.IllegalStateException: Not building!" But not all of the time. I can send the Crash report if you want, could not find a lot of sensitive info.

**Comment by VixelCreates** [comment]
thanks for checking the info
the error that you mentioned doesn't seem to be addressing any related issue with the resourcepack
it could be a mod causing this crash
you can look for any mod name that is mentioned in the errors and try removing it
if you needed any help with this you can contact me on discord (vixelcreates) and i'll help you with the issue
