### ISSUE TITLE
Incompatible with Continuity mod

### ISSUE THREAD

**Issue by DaffierDragon15** [VixelCreates/VanillaEvolved#7]
It would not let me load the recourse pack when I had the Continuity mod until I removed it which it fixed the issue.

**Comment by VixelCreates** [comment]
Hi!, thank you for your report
There was another report from a user with a similar problem to yours.
Personally, I haven't encountered any continuity issues during my testing so far.
It would be great if you could check the log files for the Minecraft instance you are experiencing problems with and report back.
