### ISSUE TITLE
Game crash when opening inventory with a tool/weapon in hand

### ISSUE THREAD

**Issue by Graidh-Gaol** [VixelCreates/VanillaEvolved#8]
As title really, not much more I can say.  This is in 1.21 with the latest version 1.12.0.  Inventory opens fine if I open it without a tool/weapon in hand but as soon as I put one in hand it crashes.

**Comment by VixelCreates** [comment]
Hi! Hope you are well!
This seems to be a problem that happens when using a mod and may not be related to ResourcePack.
If you could check for the crash error message and report back, I'd be happy to help you with this.
