### ISSUE TITLE
Goat Horn item texture barely showing

### ISSUE THREAD

**Issue by chunkybubble** [VixelCreates/VanillaEvolved#9]
The goat horn texture barely shows when holding in hand or in inventory/chest/hotbar etc.

![2024-07-03_23 24 46](https://github.com/user-attachments/assets/bf214b27-7e2f-4c7a-ac78-dde46fedecc7)

Looks normal when blowing the horn

**Comment by VixelCreates** [comment]
Hi! thanks for reporting this issue
i'll add a fix for the next update
